#Workflow CI/CD - FastAPI
#Definir proceso de automatizacion

name: FastApi CI/CD
run-name: ${{github.actor}} esta automatizando procesos!
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: themidnightguy/fastapi-quickstart

jobs:
  #JOB-N1
  python-poetry:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
#Check
    steps:
    - name: Chequeo de código
      uses: actions/checkout@v4
#Cache ci/cd
    - name: Cache de runner en Poetry (Para posterior instalacion de dependencias)
      uses: actions/cache@v4
      with:
        path: ~/.cache/pypoetry
        key: ${{runner.os}}-poetry-${{hashFiles('**/poetry.lock')}}
        restore-keys: |
          ${{runner.os}}-poetry    
#Python
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.0"
#Poetry
    - name: Instalar poetry
      run: pip install poetry
    - name: Instalar dependencias
      run: poetry install --no-interaction --no-ansi
#Pytest
    - name: Test con pytest
      run: poetry run pytest --cov=app
#GHCR
    - name: LogIn to GHCR (GitHub Container Registry)
      uses: docker/login-action@v3
      with:
            registry: ${{ env.REGISTRY}}
            username: ${{ github.actor}}
            password: ${{ secrets.GITHUB_TOKEN}}
#Docker GHCR
    - name: Build image
      run: docker build -t ${{env.REGISTRY}}/${{env.IMAGE_NAME}}/my_fastapi_app .

    - name: Push image
      run: docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}/my_fastapi_app

#Deploy servidor
  #JOB-N2
  
  Deploy_Docker_image:
    needs: python-poetry
    runs-on: ubuntu-latest
    steps:
      - name: SSH-ACTION - Docker compose up
        uses: appleboy/ssh-action@v1
        with:
         host: ${{secrets.SSH_HOST}}
         username: ${{secrets.SSH_USER}}
         key: ${{secrets.SSH_PRIVATE_KEY}}
         #¿Qué se hara en el script?
         # Se inicia sesión en docker
         # Obtenemos de imagen docker
         # Listamos imagenes y removemos los residuos
         # Detenemos y borramos el servicio que se ejecutaba anteriormente (docker image prune + flag '-f' para forzar el borrado)
         # Se levanta el servicio de fastAPI desde el archivo docker compose (desde /.deploy)
         # Desglose docker compose -> docker compose -f(desde archivo) up <servicio a levantar> -d(Ejecución en segundo plano)
         # Se valida la ejecución del contenedor listado de contenedores Docker
         script: |
          echo "---Comandos en OCI---"
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{env.REGISTRY}} -u ${{ github.actor }} --password-stdin
          
          echo "---Hacemos pull para obtener ultima version de imagen---"
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/my_fastapi_app:latest
          
          echo "---Listando contenedores Docker---"
          docker ps -a

          echo "---Detenemos y borramos fastapi-app---"
          docker stop deploy-service_fastapi_app-1 || true
          docker rm deploy-service_fastapi_app-1 || true

          echo "---Directorio .deploy/fastapi_quickstart---"
          cd ~/.deploy/fastapi-quickstart
          ls -a

          echo "---Levantando fastAPI desde docker compose"
          docker compose -f docker-compose.yml up service_fastapi_app -d

          echo "Esperando que FastAPI inicie..."
          sleep 5

          echo "---Listando contenedores Docker---"
          docker ps -a

          echo "---Removemos imagenes 'untagged'---"
          docker image prune -f

          echo "---Verificamos borrado de imagenes 'untagged'---"
          docker images -a










 